# Generated by Django 4.2.4 on 2023-09-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
